version: '3.8'

services:
  arm:
    image: webserver
    networks: 
      net:
        ipv4_address: 192.168.22.2
  frontend:
    image: webserver
    ports:
      - "81:443"
      - "82:80"
    networks: 
      net:
        ipv4_address: 192.168.22.50
        aliases:
          - frontnginx.local.net
    volumes:
      - /home/geo/musor/nginx_prox/front/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/geo/musor/nginx_prox/ssl_crt/:/etc/nginx/ssl/
  backend:
    image: webserver
    networks: 
      net:
        ipv4_address: 192.168.22.60
        aliases:
          - test-admin.local.net
    volumes:
      - /home/geo/musor/nginx_prox/site-content/index.html:/usr/share/nginx/html/index.html
      - /home/geo/musor/nginx_prox/backend/default.conf:/etc/nginx/conf.d/default.conf
      - /home/geo/musor/nginx_prox/backend/nginx.conf:/etc/nginx/nginx.conf
      - /home/geo/musor/nginx_prox/ssl_crt/:/etc/nginx/ssl/
    ports:
      - "83:443"
networks: 
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.22.0/24

   

    
