version: '3.8'

services:
  arm:
    image: webserver
    networks: 
      frontend:
        ipv4_address: 192.168.22.2
      backend:
        ipv4_address: 192.168.33.2
  frontend:
    image: webserver
    ports:
      - "81:80"
    networks: 
      frontend:
        ipv4_address: 192.168.22.3
      backend:
        ipv4_address: 192.168.33.3
    volumes:
      - /home/geo/musor/2_nginx/my-nginx/front/nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: webserver
    networks: 
      backend:
        ipv4_address: 192.168.33.4
    volumes:
      - /home/geo/musor/2_nginx/my-nginx/site-content/index.html:/usr/share/nginx/html/index.html
      - /home/geo/musor/2_nginx/my-nginx/bekend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
networks: 
  frontend:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.22.0/24

  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.33.0/24

   

    
